[project]
name = "vico"
version = "0.1.0"
description = "A Python service for inference and memory management"
requires-python = ">=3.9"
dependencies = [
    "fastapi",
    "huggingface-hub",
    "mlx-vlm",
    "mlx-lm>=0.26.2",
    "pillow",
    "pydantic",
    "duckdb"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["python"] 